// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteSubjectReader is a Reader for the DeleteSubject structure.
type DeleteSubjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSubjectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteSubjectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteSubjectNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteSubjectInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteSubjectOK creates a DeleteSubjectOK with default headers values
func NewDeleteSubjectOK() *DeleteSubjectOK {
	return &DeleteSubjectOK{}
}

/*DeleteSubjectOK handles this case with default header values.

successful operation
*/
type DeleteSubjectOK struct {
	Payload []int32
}

func (o *DeleteSubjectOK) Error() string {
	return fmt.Sprintf("[DELETE /subjects/{subject}][%d] deleteSubjectOK  %+v", 200, o.Payload)
}

func (o *DeleteSubjectOK) GetPayload() []int32 {
	return o.Payload
}

func (o *DeleteSubjectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSubjectNotFound creates a DeleteSubjectNotFound with default headers values
func NewDeleteSubjectNotFound() *DeleteSubjectNotFound {
	return &DeleteSubjectNotFound{}
}

/*DeleteSubjectNotFound handles this case with default header values.

Error code 40401 -- Subject not found
*/
type DeleteSubjectNotFound struct {
}

func (o *DeleteSubjectNotFound) Error() string {
	return fmt.Sprintf("[DELETE /subjects/{subject}][%d] deleteSubjectNotFound ", 404)
}

func (o *DeleteSubjectNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSubjectInternalServerError creates a DeleteSubjectInternalServerError with default headers values
func NewDeleteSubjectInternalServerError() *DeleteSubjectInternalServerError {
	return &DeleteSubjectInternalServerError{}
}

/*DeleteSubjectInternalServerError handles this case with default header values.

Error code 50001 -- Error in the backend datastore
*/
type DeleteSubjectInternalServerError struct {
}

func (o *DeleteSubjectInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /subjects/{subject}][%d] deleteSubjectInternalServerError ", 500)
}

func (o *DeleteSubjectInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
