// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetModeParams creates a new GetModeParams object
// with the default values initialized.
func NewGetModeParams() *GetModeParams {
	var ()
	return &GetModeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetModeParamsWithTimeout creates a new GetModeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetModeParamsWithTimeout(timeout time.Duration) *GetModeParams {
	var ()
	return &GetModeParams{

		timeout: timeout,
	}
}

// NewGetModeParamsWithContext creates a new GetModeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetModeParamsWithContext(ctx context.Context) *GetModeParams {
	var ()
	return &GetModeParams{

		Context: ctx,
	}
}

// NewGetModeParamsWithHTTPClient creates a new GetModeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetModeParamsWithHTTPClient(client *http.Client) *GetModeParams {
	var ()
	return &GetModeParams{
		HTTPClient: client,
	}
}

/*GetModeParams contains all the parameters to send to the API endpoint
for the get mode operation typically these are written to a http.Request
*/
type GetModeParams struct {

	/*Subject*/
	Subject string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get mode params
func (o *GetModeParams) WithTimeout(timeout time.Duration) *GetModeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get mode params
func (o *GetModeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get mode params
func (o *GetModeParams) WithContext(ctx context.Context) *GetModeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get mode params
func (o *GetModeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get mode params
func (o *GetModeParams) WithHTTPClient(client *http.Client) *GetModeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get mode params
func (o *GetModeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSubject adds the subject to the get mode params
func (o *GetModeParams) WithSubject(subject string) *GetModeParams {
	o.SetSubject(subject)
	return o
}

// SetSubject adds the subject to the get mode params
func (o *GetModeParams) SetSubject(subject string) {
	o.Subject = subject
}

// WriteToRequest writes these params to a swagger request
func (o *GetModeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param subject
	if err := r.SetPathParam("subject", o.Subject); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
