// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dblooman/schema-registry-client/models"
)

// GetVersionsReader is a Reader for the GetVersions structure.
type GetVersionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVersionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetVersionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetVersionsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetVersionsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetVersionsOK creates a GetVersionsOK with default headers values
func NewGetVersionsOK() *GetVersionsOK {
	return &GetVersionsOK{}
}

/*GetVersionsOK handles this case with default header values.

successful operation
*/
type GetVersionsOK struct {
	Payload []*models.SubjectVersion
}

func (o *GetVersionsOK) Error() string {
	return fmt.Sprintf("[GET /schemas/ids/{id}/versions][%d] getVersionsOK  %+v", 200, o.Payload)
}

func (o *GetVersionsOK) GetPayload() []*models.SubjectVersion {
	return o.Payload
}

func (o *GetVersionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVersionsNotFound creates a GetVersionsNotFound with default headers values
func NewGetVersionsNotFound() *GetVersionsNotFound {
	return &GetVersionsNotFound{}
}

/*GetVersionsNotFound handles this case with default header values.

Error code 40403 -- Schema not found

*/
type GetVersionsNotFound struct {
}

func (o *GetVersionsNotFound) Error() string {
	return fmt.Sprintf("[GET /schemas/ids/{id}/versions][%d] getVersionsNotFound ", 404)
}

func (o *GetVersionsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetVersionsInternalServerError creates a GetVersionsInternalServerError with default headers values
func NewGetVersionsInternalServerError() *GetVersionsInternalServerError {
	return &GetVersionsInternalServerError{}
}

/*GetVersionsInternalServerError handles this case with default header values.

Error code 50001 -- Error in the backend data store

*/
type GetVersionsInternalServerError struct {
}

func (o *GetVersionsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /schemas/ids/{id}/versions][%d] getVersionsInternalServerError ", 500)
}

func (o *GetVersionsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
