// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetClusterIDParams creates a new GetClusterIDParams object
// with the default values initialized.
func NewGetClusterIDParams() *GetClusterIDParams {

	return &GetClusterIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetClusterIDParamsWithTimeout creates a new GetClusterIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetClusterIDParamsWithTimeout(timeout time.Duration) *GetClusterIDParams {

	return &GetClusterIDParams{

		timeout: timeout,
	}
}

// NewGetClusterIDParamsWithContext creates a new GetClusterIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetClusterIDParamsWithContext(ctx context.Context) *GetClusterIDParams {

	return &GetClusterIDParams{

		Context: ctx,
	}
}

// NewGetClusterIDParamsWithHTTPClient creates a new GetClusterIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetClusterIDParamsWithHTTPClient(client *http.Client) *GetClusterIDParams {

	return &GetClusterIDParams{
		HTTPClient: client,
	}
}

/*GetClusterIDParams contains all the parameters to send to the API endpoint
for the get cluster Id operation typically these are written to a http.Request
*/
type GetClusterIDParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get cluster Id params
func (o *GetClusterIDParams) WithTimeout(timeout time.Duration) *GetClusterIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cluster Id params
func (o *GetClusterIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cluster Id params
func (o *GetClusterIDParams) WithContext(ctx context.Context) *GetClusterIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cluster Id params
func (o *GetClusterIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cluster Id params
func (o *GetClusterIDParams) WithHTTPClient(client *http.Client) *GetClusterIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cluster Id params
func (o *GetClusterIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetClusterIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
