// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetSchemaOnlyParams creates a new GetSchemaOnlyParams object
// with the default values initialized.
func NewGetSchemaOnlyParams() *GetSchemaOnlyParams {
	var ()
	return &GetSchemaOnlyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSchemaOnlyParamsWithTimeout creates a new GetSchemaOnlyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSchemaOnlyParamsWithTimeout(timeout time.Duration) *GetSchemaOnlyParams {
	var ()
	return &GetSchemaOnlyParams{

		timeout: timeout,
	}
}

// NewGetSchemaOnlyParamsWithContext creates a new GetSchemaOnlyParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSchemaOnlyParamsWithContext(ctx context.Context) *GetSchemaOnlyParams {
	var ()
	return &GetSchemaOnlyParams{

		Context: ctx,
	}
}

// NewGetSchemaOnlyParamsWithHTTPClient creates a new GetSchemaOnlyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSchemaOnlyParamsWithHTTPClient(client *http.Client) *GetSchemaOnlyParams {
	var ()
	return &GetSchemaOnlyParams{
		HTTPClient: client,
	}
}

/*GetSchemaOnlyParams contains all the parameters to send to the API endpoint
for the get schema only operation typically these are written to a http.Request
*/
type GetSchemaOnlyParams struct {

	/*Deleted*/
	Deleted *bool
	/*Subject
	  Name of the Subject

	*/
	Subject string
	/*Version
	  Version of the schema to be returned. Valid values for versionId are between [1,2^31-1] or the string "latest". "latest" returns the last registered schema under the specified subject. Note that there may be a new latest schema that gets registered right after this request is served.

	*/
	Version string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get schema only params
func (o *GetSchemaOnlyParams) WithTimeout(timeout time.Duration) *GetSchemaOnlyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get schema only params
func (o *GetSchemaOnlyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get schema only params
func (o *GetSchemaOnlyParams) WithContext(ctx context.Context) *GetSchemaOnlyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get schema only params
func (o *GetSchemaOnlyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get schema only params
func (o *GetSchemaOnlyParams) WithHTTPClient(client *http.Client) *GetSchemaOnlyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get schema only params
func (o *GetSchemaOnlyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeleted adds the deleted to the get schema only params
func (o *GetSchemaOnlyParams) WithDeleted(deleted *bool) *GetSchemaOnlyParams {
	o.SetDeleted(deleted)
	return o
}

// SetDeleted adds the deleted to the get schema only params
func (o *GetSchemaOnlyParams) SetDeleted(deleted *bool) {
	o.Deleted = deleted
}

// WithSubject adds the subject to the get schema only params
func (o *GetSchemaOnlyParams) WithSubject(subject string) *GetSchemaOnlyParams {
	o.SetSubject(subject)
	return o
}

// SetSubject adds the subject to the get schema only params
func (o *GetSchemaOnlyParams) SetSubject(subject string) {
	o.Subject = subject
}

// WithVersion adds the version to the get schema only params
func (o *GetSchemaOnlyParams) WithVersion(version string) *GetSchemaOnlyParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get schema only params
func (o *GetSchemaOnlyParams) SetVersion(version string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetSchemaOnlyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Deleted != nil {

		// query param deleted
		var qrDeleted bool
		if o.Deleted != nil {
			qrDeleted = *o.Deleted
		}
		qDeleted := swag.FormatBool(qrDeleted)
		if qDeleted != "" {
			if err := r.SetQueryParam("deleted", qDeleted); err != nil {
				return err
			}
		}

	}

	// path param subject
	if err := r.SetPathParam("subject", o.Subject); err != nil {
		return err
	}

	// path param version
	if err := r.SetPathParam("version", o.Version); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
