// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSchemaTypesParams creates a new GetSchemaTypesParams object
// with the default values initialized.
func NewGetSchemaTypesParams() *GetSchemaTypesParams {

	return &GetSchemaTypesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSchemaTypesParamsWithTimeout creates a new GetSchemaTypesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSchemaTypesParamsWithTimeout(timeout time.Duration) *GetSchemaTypesParams {

	return &GetSchemaTypesParams{

		timeout: timeout,
	}
}

// NewGetSchemaTypesParamsWithContext creates a new GetSchemaTypesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSchemaTypesParamsWithContext(ctx context.Context) *GetSchemaTypesParams {

	return &GetSchemaTypesParams{

		Context: ctx,
	}
}

// NewGetSchemaTypesParamsWithHTTPClient creates a new GetSchemaTypesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSchemaTypesParamsWithHTTPClient(client *http.Client) *GetSchemaTypesParams {

	return &GetSchemaTypesParams{
		HTTPClient: client,
	}
}

/*GetSchemaTypesParams contains all the parameters to send to the API endpoint
for the get schema types operation typically these are written to a http.Request
*/
type GetSchemaTypesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get schema types params
func (o *GetSchemaTypesParams) WithTimeout(timeout time.Duration) *GetSchemaTypesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get schema types params
func (o *GetSchemaTypesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get schema types params
func (o *GetSchemaTypesParams) WithContext(ctx context.Context) *GetSchemaTypesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get schema types params
func (o *GetSchemaTypesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get schema types params
func (o *GetSchemaTypesParams) WithHTTPClient(client *http.Client) *GetSchemaTypesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get schema types params
func (o *GetSchemaTypesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSchemaTypesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
