// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dblooman/schema-registry-client/models"
)

// RegisterReader is a Reader for the Register structure.
type RegisterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RegisterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRegisterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 409:
		result := NewRegisterConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewRegisterUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRegisterInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRegisterOK creates a RegisterOK with default headers values
func NewRegisterOK() *RegisterOK {
	return &RegisterOK{}
}

/*RegisterOK handles this case with default header values.

successful operation
*/
type RegisterOK struct {
	Payload *models.RegisterSchemaResponse
}

func (o *RegisterOK) Error() string {
	return fmt.Sprintf("[POST /subjects/{subject}/versions][%d] registerOK  %+v", 200, o.Payload)
}

func (o *RegisterOK) GetPayload() *models.RegisterSchemaResponse {
	return o.Payload
}

func (o *RegisterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RegisterSchemaResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRegisterConflict creates a RegisterConflict with default headers values
func NewRegisterConflict() *RegisterConflict {
	return &RegisterConflict{}
}

/*RegisterConflict handles this case with default header values.

Incompatible schema
*/
type RegisterConflict struct {
}

func (o *RegisterConflict) Error() string {
	return fmt.Sprintf("[POST /subjects/{subject}/versions][%d] registerConflict ", 409)
}

func (o *RegisterConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRegisterUnprocessableEntity creates a RegisterUnprocessableEntity with default headers values
func NewRegisterUnprocessableEntity() *RegisterUnprocessableEntity {
	return &RegisterUnprocessableEntity{}
}

/*RegisterUnprocessableEntity handles this case with default header values.

Error code 42201 -- Invalid schema or schema type
*/
type RegisterUnprocessableEntity struct {
}

func (o *RegisterUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /subjects/{subject}/versions][%d] registerUnprocessableEntity ", 422)
}

func (o *RegisterUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRegisterInternalServerError creates a RegisterInternalServerError with default headers values
func NewRegisterInternalServerError() *RegisterInternalServerError {
	return &RegisterInternalServerError{}
}

/*RegisterInternalServerError handles this case with default header values.

Error code 50001 -- Error in the backend data store
Error code 50002 -- Operation timed out
Error code 50003 -- Error while forwarding the request to the primary
*/
type RegisterInternalServerError struct {
}

func (o *RegisterInternalServerError) Error() string {
	return fmt.Sprintf("[POST /subjects/{subject}/versions][%d] registerInternalServerError ", 500)
}

func (o *RegisterInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
