// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/dblooman/schema-registry-client/models"
)

// NewUpdateTopLevelConfigParams creates a new UpdateTopLevelConfigParams object
// with the default values initialized.
func NewUpdateTopLevelConfigParams() *UpdateTopLevelConfigParams {
	var ()
	return &UpdateTopLevelConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateTopLevelConfigParamsWithTimeout creates a new UpdateTopLevelConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateTopLevelConfigParamsWithTimeout(timeout time.Duration) *UpdateTopLevelConfigParams {
	var ()
	return &UpdateTopLevelConfigParams{

		timeout: timeout,
	}
}

// NewUpdateTopLevelConfigParamsWithContext creates a new UpdateTopLevelConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateTopLevelConfigParamsWithContext(ctx context.Context) *UpdateTopLevelConfigParams {
	var ()
	return &UpdateTopLevelConfigParams{

		Context: ctx,
	}
}

// NewUpdateTopLevelConfigParamsWithHTTPClient creates a new UpdateTopLevelConfigParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateTopLevelConfigParamsWithHTTPClient(client *http.Client) *UpdateTopLevelConfigParams {
	var ()
	return &UpdateTopLevelConfigParams{
		HTTPClient: client,
	}
}

/*UpdateTopLevelConfigParams contains all the parameters to send to the API endpoint
for the update top level config operation typically these are written to a http.Request
*/
type UpdateTopLevelConfigParams struct {

	/*Body
	  Config Update Request

	*/
	Body *models.ConfigUpdateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update top level config params
func (o *UpdateTopLevelConfigParams) WithTimeout(timeout time.Duration) *UpdateTopLevelConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update top level config params
func (o *UpdateTopLevelConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update top level config params
func (o *UpdateTopLevelConfigParams) WithContext(ctx context.Context) *UpdateTopLevelConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update top level config params
func (o *UpdateTopLevelConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update top level config params
func (o *UpdateTopLevelConfigParams) WithHTTPClient(client *http.Client) *UpdateTopLevelConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update top level config params
func (o *UpdateTopLevelConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update top level config params
func (o *UpdateTopLevelConfigParams) WithBody(body *models.ConfigUpdateRequest) *UpdateTopLevelConfigParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update top level config params
func (o *UpdateTopLevelConfigParams) SetBody(body *models.ConfigUpdateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateTopLevelConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
