// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CompatibilityCheckResponse compatibility check response
//
// swagger:model CompatibilityCheckResponse
type CompatibilityCheckResponse struct {

	// is compatible
	IsCompatible bool `json:"is_compatible,omitempty"`
}

// Validate validates this compatibility check response
func (m *CompatibilityCheckResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CompatibilityCheckResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CompatibilityCheckResponse) UnmarshalBinary(b []byte) error {
	var res CompatibilityCheckResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
