// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SchemaReference schema reference
//
// swagger:model SchemaReference
type SchemaReference struct {

	// name
	Name string `json:"name,omitempty"`

	// subject
	Subject string `json:"subject,omitempty"`

	// version
	Version int32 `json:"version,omitempty"`
}

// Validate validates this schema reference
func (m *SchemaReference) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SchemaReference) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SchemaReference) UnmarshalBinary(b []byte) error {
	var res SchemaReference
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
