// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServerClusterID server cluster Id
//
// swagger:model ServerClusterId
type ServerClusterID struct {

	// id
	ID string `json:"id,omitempty"`

	// scope
	// Read Only: true
	Scope map[string]interface{} `json:"scope,omitempty"`
}

// Validate validates this server cluster Id
func (m *ServerClusterID) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServerClusterID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServerClusterID) UnmarshalBinary(b []byte) error {
	var res ServerClusterID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
